apiVersion: v1
kind: Service
metadata:
  name: nexus-agent
  labels:
    app: nexus-agent
spec:
  type: ClusterIP
  selector:
    app: nexus-agent
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
