"""add_keywords_aliases

Revision ID: 001b70671b50
Revises: b491318bcc31
Create Date: 2026-07-24 22:21:42.166330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001b70671b50'
down_revision: Union[str, None] = 'b491318bcc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True, comment='Precomputed routing keywords for dynamic tool matching'))
    op.add_column('tool', sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True, comment='Alternative names/phrases users may say'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'aliases')
    op.drop_column('tool', 'keywords')
    # ### end Alembic commands ###
