"""add_memory_and_observability_fields

Revision ID: 2a475ec2e137
Revises: b0a16b06227f
Create Date: 2026-07-22 01:41:50.053805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a475ec2e137'
down_revision: Union[str, None] = 'b0a16b06227f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affinity_edges',
        sa.Column('source', sa.String(length=255), nullable=False, comment='Source tool name'),
        sa.Column('target', sa.String(length=255), nullable=False, comment='Target tool name'),
        sa.Column('weight', sa.Float(), nullable=False, comment='P(target|source)'),
        sa.Column('pmi', sa.Float(), nullable=True, comment='Pointwise Mutual Information'),
        sa.Column('success_count', sa.Integer(), nullable=False, comment='Total co-occurrences'),
        sa.Column('failure_count', sa.Integer(), nullable=False, comment='Failed co-occurrences'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Last update timestamp'),
        sa.PrimaryKeyConstraint('source', 'target', name=op.f('pk_affinity_edges'))
    )
    op.create_table('invocation_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='Conversation session ID'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='LLM model used'),
    sa.Column('total_cost_usd', sa.Float(), nullable=False, comment='Total cost in USD'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total tokens consumed'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='Total execution time in ms'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the invocation completed without errors'),
    sa.Column('reflection_score', sa.Float(), nullable=True, comment='Final reflection quality score (0-10)'),
    sa.Column('tool_count', sa.Integer(), nullable=False, comment='Number of tool calls made'),
    sa.Column('tool_error_count', sa.Integer(), nullable=False, comment='Number of tool calls that failed'),
    sa.Column('response_type', sa.String(length=50), nullable=True, comment='tool | greeting | meta | memory_query'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if invocation failed'),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Prompt name -> version mapping'),
    sa.Column('cost_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Cost breakdown by model'),
    sa.Column('ab_experiment_id', sa.String(length=100), nullable=True, comment='A/B experiment identifier'),
    sa.Column('ab_variant', sa.String(length=100), nullable=True, comment='A/B variant assigned'),
    sa.Column('outcome_version', sa.Integer(), nullable=False, comment='Schema version for forward compatibility'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invocation_outcomes'))
    )
    op.create_index(op.f('ix_invocation_outcomes_created_at'), 'invocation_outcomes', ['created_at'], unique=False)
    op.create_index(op.f('ix_invocation_outcomes_session_id'), 'invocation_outcomes', ['session_id'], unique=False)
    op.add_column('memory', sa.Column('status', sa.String(length=20), nullable=True, comment='active | deprecated | archived'))
    op.add_column('memory', sa.Column('consolidated_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='UUIDs of source memories merged into this one'))
    op.add_column('memory', sa.Column('access_count', sa.Integer(), nullable=False, server_default=sa.text('0'), comment='Number of times this memory was retrieved'))
    op.add_column('memory', sa.Column('base_importance', sa.Float(), nullable=True, comment='Original importance score (before decay)'))
    op.add_column('memory', sa.Column('current_importance', sa.Float(), nullable=True, comment='Current importance score (after decay)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory', 'current_importance')
    op.drop_column('memory', 'base_importance')
    op.drop_column('memory', 'access_count')
    op.drop_column('memory', 'consolidated_from')
    op.drop_column('memory', 'status')
    op.drop_index(op.f('ix_invocation_outcomes_session_id'), table_name='invocation_outcomes')
    op.drop_index(op.f('ix_invocation_outcomes_created_at'), table_name='invocation_outcomes')
    op.drop_table('invocation_outcomes')
    op.drop_table('affinity_edges')
    # ### end Alembic commands ###
