"""init

Revision ID: 417bcd711761
Revises: 
Create Date: 2026-07-20 16:32:01.258040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '417bcd711761'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False, comment='Session title'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Session status: active | archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary session metadata'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_table('tool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique tool name'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description'),
    sa.Column('purpose', sa.Text(), nullable=False, comment='What the tool does and when to use it'),
    sa.Column('endpoint_url', sa.String(length=2048), nullable=False, comment='API endpoint URL'),
    sa.Column('http_method', sa.String(length=10), nullable=False, comment='HTTP method: GET | POST | PUT | DELETE | PATCH'),
    sa.Column('auth_type', sa.String(length=50), nullable=False, comment='Authentication type'),
    sa.Column('auth_ref', sa.String(length=255), nullable=False, comment='Reference to stored auth config'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for input parameters'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for output'),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Business validation rules'),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Example invocations'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='Categorization tags'),
    sa.Column('category', sa.String(length=255), nullable=False, comment='Functional category'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='Requires HITL approval'),
    sa.Column('risk_level', sa.String(length=50), nullable=False, comment='Risk level: low | medium | high'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether the tool is active'),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True, comment='Max requests per minute (null = unlimited)'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Semantic embedding for discovery'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Tool definition version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool')),
    sa.UniqueConstraint('name', name=op.f('uq_tool_name'))
    )
    op.create_table('agent_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('graph_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of the LangGraph state'),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Agent's plan steps"),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Run status: running | completed | failed | interrupted | cancelled'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='When execution finished'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total LLM tokens consumed'),
    sa.Column('total_cost_usd', sa.Float(), nullable=False, comment='Total cost in USD'),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=True, comment='LangGraph checkpointer checkpoint ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_agent_run_session_id_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run'))
    )
    op.create_table('memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Optional originating session'),
    sa.Column('kind', sa.String(length=50), nullable=False, comment='Memory kind: episodic | semantic | procedural | preference'),
    sa.Column('content', sa.Text(), nullable=False, comment='Memory content text'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Vector embedding for semantic search'),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary memory metadata'),
    sa.Column('importance', sa.Float(), nullable=False, comment='Relative importance score (0-1)'),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='Last time this memory was retrieved'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_memory_session_id_session'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory'))
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Message role: user | assistant | tool | system'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Rich content blocks (JSON)'),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Tool call invocations (JSON)'),
    sa.Column('parent_message_id', sa.UUID(), nullable=True, comment='Parent message ID for branching'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['message.id'], name=op.f('fk_message_parent_message_id_message'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_message_session_id_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('toolversion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Snapshot version number'),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full tool definition at this version'),
    sa.Column('changed_by', sa.String(length=255), nullable=True, comment='Actor who made the change'),
    sa.Column('change_comment', sa.Text(), nullable=True, comment='Reason or description of the change'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_toolversion_tool_id_tool'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_toolversion'))
    )
    op.create_index(op.f('ix_toolversion_tool_id'), 'toolversion', ['tool_id'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('tool_call', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The tool call that needs approval'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Approval status: pending | approved | rejected | edited'),
    sa.Column('decision_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Modified payload or rejection reason'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True, comment='When decision was made'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], name=op.f('fk_approval_agent_run_id_agent_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    op.create_table('tool_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Input arguments sent to the tool'),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw response from the tool'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Execution outcome: success | error | timeout | interrupted'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='HTTP response status code'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='Execution duration in milliseconds'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('retried', sa.Boolean(), nullable=False, comment='Whether this was a retry'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], name=op.f('fk_tool_execution_agent_run_id_agent_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_tool_execution_session_id_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_tool_execution_tool_id_tool'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_execution'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_execution')
    op.drop_table('approval')
    op.drop_index(op.f('ix_toolversion_tool_id'), table_name='toolversion')
    op.drop_table('toolversion')
    op.drop_table('message')
    op.drop_table('memory')
    op.drop_table('agent_run')
    op.drop_table('tool')
    op.drop_table('session')
    # ### end Alembic commands ###
