"""artifact registry self fk

Revision ID: 556c8a902f17
Revises: de512bf174c1
Create Date: 2026-08-04 14:59:05.268362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556c8a902f17'
down_revision: Union[str, None] = 'de512bf174c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_artifact_registry_parent_artifact_id_artifact_registry'), 'artifact_registry', 'artifact_registry', ['parent_artifact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_artifact_registry_parent_artifact_id_artifact_registry'), 'artifact_registry', type_='foreignkey')
    # ### end Alembic commands ###
