"""production_ready_schema

Revision ID: 5f5863421589
Revises: f0e1d2c3b4a5
Create Date: 2026-08-02 04:11:48.284829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f5863421589'
down_revision: Union[str, None] = 'f0e1d2c3b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True, comment='Actor (user id or system)'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Action type (tool_executed, approval_approved, ...)'),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='Resource kind (tool, session, workflow)'),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='State before the action'),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='State after the action'),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_session_id'), 'audit_log', ['session_id'], unique=False)
    op.create_table('capability_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False, comment='Capability id this snapshot belongs to'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number'),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full capability contract snapshot'),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('change_comment', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether this version is the active one'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_version'))
    )
    op.create_index(op.f('ix_capability_version_capability_id'), 'capability_version', ['capability_id'], unique=False)
    op.create_table('compensation_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('original_tool', sa.String(length=255), nullable=False, comment='Tool whose side effect is compensated'),
    sa.Column('original_tool_id', sa.UUID(), nullable=True),
    sa.Column('compensating_operation', sa.String(length=255), nullable=False, comment='Compensating operation (from metadata)'),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending | success | failed | skipped'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compensation_log'))
    )
    op.create_index(op.f('ix_compensation_log_session_id'), 'compensation_log', ['session_id'], unique=False)
    op.create_table('dead_letter_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False, comment='Name of the tool that failed'),
    sa.Column('tool_id', sa.UUID(), nullable=True, comment='Tool definition ID'),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The input arguments that were passed'),
    sa.Column('error_message', sa.Text(), nullable=False, comment='The final error message'),
    sa.Column('error_code', sa.String(length=100), nullable=False, comment='Machine-readable error code'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retries attempted'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='DLQ status: pending | replayed | archived'),
    sa.Column('original_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the original failure occurred'),
    sa.Column('last_retry_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last retry'),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True, comment='When this was replayed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_execution'))
    )
    op.create_table('environment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Environment name (dev, staging, prod)'),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('endpoint_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Per-capability endpoint overrides for this environment'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environment')),
    sa.UniqueConstraint('name', name=op.f('uq_environment_name'))
    )
    op.create_table('outbox_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Domain event type'),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False, comment='Aggregate (session, task, workflow)'),
    sa.Column('aggregate_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending | published | failed'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='Publish attempts'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event'))
    )
    op.create_index(op.f('ix_outbox_event_event_type'), 'outbox_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_event_status'), 'outbox_event', ['status'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False, comment='Task type (workflow_run, report, etl, ...)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: pending | queued | running | paused | completed | failed | cancelled'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Task input payload'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Task result data'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Progress percentage (0-100)'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='Execution attempt count'),
    sa.Column('max_attempts', sa.Integer(), nullable=False, comment='Max attempts before failure'),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False, comment='Cancellation flag (checked between steps)'),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True, comment='Cron expression for scheduled runs'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_index(op.f('ix_task_next_run_at'), 'task', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_task_type'), 'task', ['task_type'], unique=False)
    op.create_table('workflow_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique workflow name'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description'),
    sa.Column('trigger_intent_pattern', sa.String(length=255), nullable=False, comment='Intent pattern used to match user requests'),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ordered workflow steps (JSONB)'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Match priority (higher first)'),
    sa.Column('max_nodes', sa.Integer(), nullable=False, comment='Max steps before dynamic hand-off'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether the workflow is active'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Workflow definition version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definition')),
    sa.UniqueConstraint('name', name=op.f('uq_workflow_definition_name'))
    )
    op.create_table('workflow_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False, comment='Workflow definition id this instance derives from'),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Conversation session (may be null for scheduled runs)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: running | paused | awaiting_approval | completed | failed | cancelled'),
    sa.Column('current_step', sa.String(length=100), nullable=True, comment='Current step id (resume point)'),
    sa.Column('collected', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Collected step inputs (resume state)'),
    sa.Column('workflow_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Compiled graph snapshot for resume'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instance'))
    )
    op.alter_column('approval_policy', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique policy name',
               existing_nullable=False)
    op.alter_column('approval_policy', 'description',
               existing_type=sa.TEXT(),
               comment='Human-readable policy description',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('approval_policy', 'trigger',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Trigger conditions: {risk_level, capability, max_amount, ...}. The longest-matching trigger wins.',
               existing_comment='Trigger conditions: {risk_level, capability, max_amount, ...}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('approval_policy', 'steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered approval chain steps. Each step: {step_id, role, ttl_seconds, escalation_role, freed_by_jsonpath}',
               existing_comment='Ordered approval chain steps',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('approval_policy', 'priority',
               existing_type=sa.INTEGER(),
               comment='Match priority (higher = applied first)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('approval_policy', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether this policy is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('approval_policy', 'version',
               existing_type=sa.INTEGER(),
               comment='Policy version',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('artifact', 'kind',
               existing_type=sa.VARCHAR(length=50),
               comment='Artifact kind: dashboard | report | dataset | config | prompt',
               existing_comment='dashboard | report | dataset | config | prompt',
               existing_nullable=False)
    op.alter_column('artifact', 'name',
               existing_type=sa.VARCHAR(length=512),
               comment='Artifact name',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact', 'parent_artifact_id',
               existing_type=sa.UUID(),
               comment='Parent artifact for branching/forking',
               existing_comment='Parent artifact for branching',
               existing_nullable=True)
    op.alter_column('artifact', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Artifact content (schema depends on kind)',
               existing_comment='Artifact content',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('artifact', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA256 of content for dedup',
               existing_comment='SHA256 of content',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact', 'version',
               existing_type=sa.INTEGER(),
               comment='Monotonic version number',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('capability', 'intent_profiles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Semantic intent → API param mappings (e.g. {'current': {'current_weather': True}})",
               existing_comment='Semantic intent to API param mappings',
               existing_nullable=True)
    op.alter_column('capability', 'input_policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Default params + computed field paths (e.g. {'defaults': {'timezone': 'auto'}})",
               existing_comment='Default params and computed field paths',
               existing_nullable=True)
    op.alter_column('capability', 'output_contract',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Expected response shape for validation (e.g. {'required_any_of': ['$.current_weather']})",
               existing_comment='Expected response shape for validation',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_capability_logical_op_name'), 'capability', type_='unique')
    op.drop_index(op.f('ix_capability_logical_op_name'), table_name='capability')
    op.create_index(op.f('ix_capability_logical_op_name'), 'capability', ['logical_op_name'], unique=True)
    op.alter_column('execution_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_comment='Event payload (result, error, timing)',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('long_running_workflow', 'session_id',
               existing_type=sa.UUID(),
               comment='Originating session',
               existing_nullable=False)
    op.alter_column('long_running_workflow', 'name',
               existing_type=sa.VARCHAR(length=512),
               comment='Human-readable workflow name',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('long_running_workflow', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status: pending | running | paused | completed | failed',
               existing_comment='pending | running | paused | completed | failed',
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('long_running_workflow', 'last_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last execution timestamp',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'next_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Next scheduled execution',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'run_count',
               existing_type=sa.INTEGER(),
               comment='Number of completed runs',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('long_running_workflow', 'max_runs',
               existing_type=sa.INTEGER(),
               comment='Max runs before auto-archiving (0 = unlimited)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('long_running_workflow', 'notify_on',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Events that trigger notification: ['complete', 'failure', 'status_change']",
               existing_comment='Events triggering notification',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('long_running_workflow', 'notification_target',
               existing_type=sa.VARCHAR(length=255),
               comment='Notification target (email, webhook URL, etc.)',
               existing_comment='Email, webhook URL, etc.',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'error_message',
               existing_type=sa.TEXT(),
               comment='Failure reason if status=failed',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Accumulated cost across all runs',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('project', 'description',
               existing_type=sa.TEXT(),
               comment='Project description',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('project', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Project status: active | archived | completed',
               existing_comment='active | archived | completed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email address',
               existing_nullable=False)
    op.alter_column('user', 'roles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='Role identifiers (e.g. manager, compliance, finance)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('user', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether the user is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('workflow_template', 'trigger_intent_pattern',
               existing_type=sa.VARCHAR(length=255),
               comment="Keyword/intent pattern to match (e.g. 'reconciliation', 'dashboard')",
               existing_comment='Keyword/intent pattern to match',
               existing_nullable=False)
    op.alter_column('workflow_template', 'capability_chain',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Ordered list of capability steps. Each step: {'capability': 'reconcile_transactions', 'inputs': {...}}",
               existing_comment='Ordered list of capability steps',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('workflow_template', 'description',
               existing_type=sa.TEXT(),
               comment='Human-readable description of the workflow',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('workflow_template', 'priority',
               existing_type=sa.INTEGER(),
               comment='Match priority (higher = matched first)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_template', 'max_nodes',
               existing_type=sa.INTEGER(),
               comment='Max nodes before decomposition is triggered',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('workflow_template', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether this template is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('workflow_template', 'version',
               existing_type=sa.INTEGER(),
               comment='Template version',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_template', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Template version',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('workflow_template', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this template is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('workflow_template', 'max_nodes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Max nodes before decomposition is triggered',
               existing_nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('workflow_template', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Match priority (higher = matched first)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('workflow_template', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable description of the workflow',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('workflow_template', 'capability_chain',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered list of capability steps',
               existing_comment="Ordered list of capability steps. Each step: {'capability': 'reconcile_transactions', 'inputs': {...}}",
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('workflow_template', 'trigger_intent_pattern',
               existing_type=sa.VARCHAR(length=255),
               comment='Keyword/intent pattern to match',
               existing_comment="Keyword/intent pattern to match (e.g. 'reconciliation', 'dashboard')",
               existing_nullable=False)
    op.alter_column('user', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the user is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user', 'roles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='Role identifiers (e.g. manager, compliance, finance)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User email address',
               existing_nullable=False)
    op.alter_column('project', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='active | archived | completed',
               existing_comment='Project status: active | archived | completed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('project', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Project description',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('long_running_workflow', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Accumulated cost across all runs',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('long_running_workflow', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Failure reason if status=failed',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'notification_target',
               existing_type=sa.VARCHAR(length=255),
               comment='Email, webhook URL, etc.',
               existing_comment='Notification target (email, webhook URL, etc.)',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'notify_on',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Events triggering notification',
               existing_comment="Events that trigger notification: ['complete', 'failure', 'status_change']",
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('long_running_workflow', 'max_runs',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Max runs before auto-archiving (0 = unlimited)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('long_running_workflow', 'run_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of completed runs',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('long_running_workflow', 'next_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Next scheduled execution',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'last_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last execution timestamp',
               existing_nullable=True)
    op.alter_column('long_running_workflow', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending | running | paused | completed | failed',
               existing_comment='Status: pending | running | paused | completed | failed',
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('long_running_workflow', 'name',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Human-readable workflow name',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('long_running_workflow', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Originating session',
               existing_nullable=False)
    op.alter_column('execution_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_comment='Event payload (result, error, timing)',
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_capability_logical_op_name'), table_name='capability')
    op.create_index(op.f('ix_capability_logical_op_name'), 'capability', ['logical_op_name'], unique=False)
    op.create_unique_constraint(op.f('uq_capability_logical_op_name'), 'capability', ['logical_op_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('capability', 'output_contract',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Expected response shape for validation',
               existing_comment="Expected response shape for validation (e.g. {'required_any_of': ['$.current_weather']})",
               existing_nullable=True)
    op.alter_column('capability', 'input_policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Default params and computed field paths',
               existing_comment="Default params + computed field paths (e.g. {'defaults': {'timezone': 'auto'}})",
               existing_nullable=True)
    op.alter_column('capability', 'intent_profiles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Semantic intent to API param mappings',
               existing_comment="Semantic intent → API param mappings (e.g. {'current': {'current_weather': True}})",
               existing_nullable=True)
    op.alter_column('artifact', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Monotonic version number',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('artifact', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA256 of content',
               existing_comment='SHA256 of content for dedup',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Artifact content',
               existing_comment='Artifact content (schema depends on kind)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('artifact', 'parent_artifact_id',
               existing_type=sa.UUID(),
               comment='Parent artifact for branching',
               existing_comment='Parent artifact for branching/forking',
               existing_nullable=True)
    op.alter_column('artifact', 'name',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Artifact name',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact', 'kind',
               existing_type=sa.VARCHAR(length=50),
               comment='dashboard | report | dataset | config | prompt',
               existing_comment='Artifact kind: dashboard | report | dataset | config | prompt',
               existing_nullable=False)
    op.alter_column('approval_policy', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Policy version',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('approval_policy', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this policy is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('approval_policy', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Match priority (higher = applied first)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('approval_policy', 'steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered approval chain steps',
               existing_comment='Ordered approval chain steps. Each step: {step_id, role, ttl_seconds, escalation_role, freed_by_jsonpath}',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('approval_policy', 'trigger',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Trigger conditions: {risk_level, capability, max_amount, ...}',
               existing_comment='Trigger conditions: {risk_level, capability, max_amount, ...}. The longest-matching trigger wins.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('approval_policy', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable policy description',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('approval_policy', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique policy name',
               existing_nullable=False)
    op.drop_table('workflow_instance')
    op.drop_table('workflow_definition')
    op.drop_index(op.f('ix_task_task_type'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_next_run_at'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_outbox_event_status'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_event_type'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_table('environment')
    op.drop_table('dead_letter_execution')
    op.drop_index(op.f('ix_compensation_log_session_id'), table_name='compensation_log')
    op.drop_table('compensation_log')
    op.drop_index(op.f('ix_capability_version_capability_id'), table_name='capability_version')
    op.drop_table('capability_version')
    op.drop_index(op.f('ix_audit_log_session_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
