"""add_interrupt_type_to_approval

Revision ID: b0a16b06227f
Revises: 417bcd711761
Create Date: 2026-07-21 02:51:52.442079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0a16b06227f'
down_revision: Union[str, None] = '417bcd711761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval', sa.Column('interrupt_type', sa.String(length=50), nullable=False, comment='Interrupt category: tool_approval | plan_review | final_review'))
    op.add_column('approval', sa.Column('interrupt_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Generic payload shown to the user for any interrupt type'))
    op.alter_column('approval', 'tool_call',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='The tool call that needs approval (tool_approval only)',
               existing_comment='The tool call that needs approval',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval', 'tool_call',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='The tool call that needs approval',
               existing_comment='The tool call that needs approval (tool_approval only)',
               existing_nullable=False)
    op.drop_column('approval', 'interrupt_payload')
    op.drop_column('approval', 'interrupt_type')
    # ### end Alembic commands ###
