"""initial_schema

Revision ID: b491318bcc31
Revises: 
Create Date: 2026-07-24 20:19:31.175704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b491318bcc31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invocation_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='Conversation session ID'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='LLM model used'),
    sa.Column('total_cost_usd', sa.Float(), nullable=False, comment='Total cost in USD'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total tokens consumed'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='Total execution time in ms'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the invocation completed without errors'),
    sa.Column('tool_count', sa.Integer(), nullable=False, comment='Number of tool calls made'),
    sa.Column('tool_error_count', sa.Integer(), nullable=False, comment='Number of tool calls that failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if invocation failed'),
    sa.Column('cost_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Cost breakdown by model'),
    sa.Column('outcome_version', sa.Integer(), nullable=False, comment='Schema version for forward compatibility'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invocation_outcomes'))
    )
    op.create_index(op.f('ix_invocation_outcomes_created_at'), 'invocation_outcomes', ['created_at'], unique=False)
    op.create_index(op.f('ix_invocation_outcomes_session_id'), 'invocation_outcomes', ['session_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False, comment='Session title'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Session status: active | archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary session metadata'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_table('tool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique tool name'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description'),
    sa.Column('purpose', sa.Text(), nullable=False, comment='What the tool does and when to use it'),
    sa.Column('endpoint_url', sa.String(length=2048), nullable=False, comment='API endpoint URL'),
    sa.Column('http_method', sa.String(length=10), nullable=False, comment='HTTP method: GET | POST | PUT | DELETE | PATCH'),
    sa.Column('auth_type', sa.String(length=50), nullable=False, comment='Authentication type'),
    sa.Column('auth_ref', sa.String(length=255), nullable=False, comment='Reference to stored auth config'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for input parameters'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for output'),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Business validation rules'),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Example invocations'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='Categorization tags'),
    sa.Column('category', sa.String(length=255), nullable=False, comment='Functional category'),
    sa.Column('risk_level', sa.String(length=50), nullable=False, comment='Risk level: low | medium | high'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether the tool is active'),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True, comment='Max requests per minute (null = unlimited)'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=4096), nullable=True, comment='Semantic embedding for discovery'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Tool definition version'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool')),
    sa.UniqueConstraint('name', name=op.f('uq_tool_name'))
    )
    op.create_table('memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Optional originating session'),
    sa.Column('kind', sa.String(length=50), nullable=False, comment='Memory kind: episodic | semantic | procedural'),
    sa.Column('content', sa.Text(), nullable=False, comment='Memory content text'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=4096), nullable=True, comment='Vector embedding for semantic search'),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary memory metadata'),
    sa.Column('importance', sa.Float(), nullable=False, comment='Relative importance score (0-1)'),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True, comment='Last time this memory was retrieved'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, comment='active | deprecated | archived'),
    sa.Column('consolidated_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='UUIDs of source memories merged into this one'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='Number of times this memory was retrieved'),
    sa.Column('base_importance', sa.Float(), nullable=True, comment='Original importance score (before decay)'),
    sa.Column('current_importance', sa.Float(), nullable=True, comment='Current importance score (after decay)'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_memory_session_id_session'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory'))
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Message role: user | assistant | tool | system'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Rich content blocks (JSON)'),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Tool call invocations (JSON)'),
    sa.Column('parent_message_id', sa.UUID(), nullable=True, comment='Parent message ID for branching'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['message.id'], name=op.f('fk_message_parent_message_id_message'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_message_session_id_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('tool_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True, comment='Agent run identifier (optional — no FK constraint)'),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Input arguments sent to the tool'),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw response from the tool'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Execution outcome: success | error | timeout | interrupted'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='HTTP response status code'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='Execution duration in milliseconds'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('retried', sa.Boolean(), nullable=False, comment='Whether this was a retry'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_tool_execution_session_id_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_tool_execution_tool_id_tool'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_execution'))
    )
    op.create_table('toolversion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Snapshot version number'),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full tool definition at this version'),
    sa.Column('changed_by', sa.String(length=255), nullable=True, comment='Actor who made the change'),
    sa.Column('change_comment', sa.Text(), nullable=True, comment='Reason or description of the change'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_toolversion_tool_id_tool'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_toolversion'))
    )
    op.create_index(op.f('ix_toolversion_tool_id'), 'toolversion', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toolversion_tool_id'), table_name='toolversion')
    op.drop_table('toolversion')
    op.drop_table('tool_execution')
    op.drop_table('message')
    op.drop_table('memory')
    op.drop_table('tool')
    op.drop_table('session')
    op.drop_index(op.f('ix_invocation_outcomes_session_id'), table_name='invocation_outcomes')
    op.drop_index(op.f('ix_invocation_outcomes_created_at'), table_name='invocation_outcomes')
    op.drop_table('invocation_outcomes')
    # ### end Alembic commands ###
