"""hot_path_indexes

Revision ID: c7f80200ca2a
Revises: 9f7a6b5c4d3e
Create Date: 2026-08-02 04:24:55.028381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f80200ca2a'
down_revision: Union[str, None] = '9f7a6b5c4d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_endpoint_provider_id'), 'endpoint', ['provider_id'], unique=False)
    op.create_index(op.f('ix_long_running_workflow_next_run_at'), 'long_running_workflow', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_long_running_workflow_status'), 'long_running_workflow', ['status'], unique=False)
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    op.create_index(op.f('ix_provider_capability_id'), 'provider', ['capability_id'], unique=False)
    op.create_index(op.f('ix_tool_execution_session_id'), 'tool_execution', ['session_id'], unique=False)
    op.create_index(op.f('ix_tool_execution_tool_id'), 'tool_execution', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_execution_tool_id'), table_name='tool_execution')
    op.drop_index(op.f('ix_tool_execution_session_id'), table_name='tool_execution')
    op.drop_index(op.f('ix_provider_capability_id'), table_name='provider')
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_index(op.f('ix_long_running_workflow_status'), table_name='long_running_workflow')
    op.drop_index(op.f('ix_long_running_workflow_next_run_at'), table_name='long_running_workflow')
    op.drop_index(op.f('ix_endpoint_provider_id'), table_name='endpoint')
    # ### end Alembic commands ###
