"""sync artifact registry comments

Revision ID: de512bf174c1
Revises: ef10aa11bb23
Create Date: 2026-08-04 14:44:16.644722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de512bf174c1'
down_revision: Union[str, None] = 'ef10aa11bb23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifact_registry', 'session_id',
               existing_type=sa.UUID(),
               comment='Owning session',
               existing_nullable=True)
    op.alter_column('artifact_registry', 'capability_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Producing capability (stable id or name)',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact_registry', 'tool_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Producing tool',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact_registry', 'type',
               existing_type=sa.VARCHAR(length=100),
               comment='Artifact type (renderer key)',
               existing_nullable=False,
               existing_server_default=sa.text("'GenericArtifact'::character varying"))
    op.alter_column('artifact_registry', 'schema_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Artifact schema version',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('artifact_registry', 'artifact_revision',
               existing_type=sa.INTEGER(),
               comment='Revision number (immutable after publication)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('artifact_registry', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='Lifecycle: created | promoted | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('artifact_registry', 'parent_artifact_id',
               existing_type=sa.UUID(),
               comment='Relationship: derived from (producer link)',
               existing_nullable=True)
    op.alter_column('artifact_registry', 'execution_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Producing execution task id',
               existing_nullable=True)
    op.alter_column('artifact_registry', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Immutable artifact payload',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifact_registry', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Immutable artifact payload',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('artifact_registry', 'execution_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Producing execution task id',
               existing_nullable=True)
    op.alter_column('artifact_registry', 'parent_artifact_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Relationship: derived from (producer link)',
               existing_nullable=True)
    op.alter_column('artifact_registry', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Lifecycle: created | promoted | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('artifact_registry', 'artifact_revision',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Revision number (immutable after publication)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('artifact_registry', 'schema_version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Artifact schema version',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('artifact_registry', 'type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Artifact type (renderer key)',
               existing_nullable=False,
               existing_server_default=sa.text("'GenericArtifact'::character varying"))
    op.alter_column('artifact_registry', 'tool_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Producing tool',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact_registry', 'capability_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Producing capability (stable id or name)',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('artifact_registry', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owning session',
               existing_nullable=True)
    # ### end Alembic commands ###
