"""add registry enrichment columns

Revision ID: f488eaa7a36f
Revises: 78c888e39c34
Create Date: 2026-08-03 11:02:11.022059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f488eaa7a36f'
down_revision: Union[str, None] = '78c888e39c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True, comment='Explicit semantic capabilities (e.g. retrieve, pokemon, game_data)'))
    op.add_column('tool', sa.Column('produces', postgresql.ARRAY(sa.String()), nullable=True, comment='Artifacts/outputs this tool produces (downstream planning)'))
    op.add_column('tool', sa.Column('consumes', postgresql.ARRAY(sa.String()), nullable=True, comment='Artifacts/inputs this tool consumes (upstream wiring)'))
    op.add_column('tool', sa.Column('related', postgresql.ARRAY(sa.String()), nullable=True, comment='Adjacent tool names for retrieval suggestions'))
    op.add_column('tool', sa.Column('cacheable', sa.Boolean(), nullable=False, comment='Quality hint: result is cacheable (true) or must be fresh (false)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'cacheable')
    op.drop_column('tool', 'related')
    op.drop_column('tool', 'consumes')
    op.drop_column('tool', 'produces')
    op.drop_column('tool', 'capabilities')
    # ### end Alembic commands ###
